# build environment
FROM node:14-alpine  as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run-script build

# production environment
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html





COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
