version: "3"

##### om en person i framtiden skulle vilja göra containerna mindre kan man byta till alpine
##### verisonen av alla images. Och använda multi stage build.

####################### DEV version 1
services:
  
  # gateway:
  #   env_file: .env
  #   container_name: gateway

  #   # Tell docker what file to build the server from
  #   build: ./gateway
  #   command: nodemon server.js
  #   volumes:
  #     - ./gateway:/app
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - back-tier

  #   # env_file: secrets/local.secrets
    

  #   # Restart action
  #   restart: always

  mongo-db:
    container_name: database

    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_clientstore:/data/db
    networks:
      - back-tier

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - back-tier


  rest:
    env_file: .env
    container_name: rest

    # Tell docker what file to build the server from
    build: ./rest
    command: nodemon server.js
    volumes:
      - ./rest:/app
    ports:
       - "3000:3000"

    networks:
      - back-tier


  simulator:
    env_file: .env
    container_name: simulator

    # Tell docker what file to build the server from
    build: ./simulator
    command: nodemon simulator.js
    volumes:
      - ./simulator:/app

    networks:
      - back-tier

    

networks:
  back-tier:

volumes:
  node_modules:
  mongodb_clientstore:
