version: "3"

##### om en person i framtiden skulle vilja göra containerna mindre kan man byta till alpine
##### verisonen av alla images. Och använda multi stage build.

####################### DEV version 1
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules" #utan denna så skriver man över när man startar
    ports:
      - "${FRONTEND_PORT_HOST}:${FRONTEND_PORT_CONTAINER}"
    environment:
      - CHOKIDAR_USEPOLLING=true
      


  mongo-db:
    container_name: database

    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_clientstore:/data/db
    networks:
      - back-tier


  rest:
    env_file: .env
    container_name: rest

    # Tell docker what file to build the server from
    build: ./rest
    command: nodemon server.js
    volumes:
      - ./rest:/app
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT_CONTAINER}"
    

    networks:
      - back-tier

  # simulator:
  #   env_file: .env
  #   container_name: simulator

  #   # Tell docker what file to build the server from
  #   build: ./simulator
  #   command: nodemon simulator.js
  #   volumes:
  #     - ./simulator:/app

  #   networks:
  #     - back-tier

networks:
  back-tier:

volumes:
  node_modules:
  mongodb_clientstore:
