version: "3"

##### om en person i framtiden skulle vilja göra containerna mindre kan man byta till alpine
##### verisonen av alla images. Och använda multi stage build.

####################### DEV version 1
services:
  gateway:
    container_name: gateway

    # Tell docker what file to build the server from
    build: ./gateway
    command: nodemon server.js
    volumes:
      - ./gateway:/app
    ports:
      - "8080:8080"
    networks:
      - back-tier

    # env_file: secrets/local.secrets
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_DATABASE: ${MONGO_DATABASE}

    # Restart action
    restart: always

  mongo-db:
    container_name: database

    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_clientstore:/data/db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - back-tier

  simulator:
    container_name: simulator

    # Tell docker what file to build the server from
    build: ./simulator
    command: nodemon simulator.js
    volumes:
      - ./simulator:/app

    networks:
      - back-tier

    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_DATABASE: ${MONGO_DATABASE}

networks:
  back-tier:

volumes:
  node_modules:
  mongodb_clientstore:
