version: "3"

##### om en person i framtiden skulle vilja göra containerna mindre kan man byta till alpine
##### verisonen av alla images. Och använda multi stage build.

####################### DEV version 1

services:
  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
       
    networks:
      - back-tier

  mongo-db:
    container_name: database

    image: mongo
    
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 3s
      timeout: 15s
      retries: 5
    restart: always
    volumes:
      - mongodb_clientstore_prod:/data/db
    networks:
      - back-tier

  rest:
    env_file: .env
    container_name: rest

    # Tell docker what file to build the server from
    
    build:
      context: ./rest
      dockerfile: Dockerfile.production
    
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT_CONTAINER}"

    networks:
      - back-tier

  simulator:
    env_file: .env
    container_name: simulator
    # Tell docker what file to build the server from
    build:
      context: ./simulator
      dockerfile: Dockerfile.production
    
    depends_on: 
      mongo-db:
        condition: service_healthy
  
    networks:
      - back-tier
  
networks:
  back-tier:
  

volumes:
  mongodb_clientstore_prod:
